### ISSUE TITLE
Convergence plans with joyent/docker-node team

### ISSUE THREAD

**Issue by rvagg** [iojs/docker-iojs#77]
As per https://github.com/joyent/docker-node/issues/28 I've added @chorrell and @dcrudgington to the @nodejs/docker team. Handing over to y'all now to discuss how to converge your resources to continue to produce both images but as a combined team. Timing and the details of how you manage both repos are entirely up to you of course. As usual if you need any resources from the Build WG then just @-mention us and we'll come running.

Happy times!

**Comment by rvagg** [comment]
Also going to ping @mhart who maintains an alpine-node container and really should be involved in this WG!

**Comment by retrohacker** [comment]
Much :heart:! Glad to be working with you all!

**Comment by Starefossen** [comment]
Awesome 😄🚀

**Comment by chorrell** [comment]
So I think we can probably just move the docker-node repo over to http://github.com/nodejs/ this week or next if everyone ls fine with that. We probably need to coordinate a few things though :)

For the short term (pre-merge) I'm fine with being the point maintainer of the docker-node image for any updates. I have admin rights to initiate the org switch, I'll just need someone to accept it on the nodejs end.

In terms of the docker-registry, we'll need to do a follow-up pull request to https://github.com/docker-library/official-images. I can handle that.

**Comment by Starefossen** [comment]
Sounds like a good plan @chorrell 😄

Are there any points in merging the two repos?

**Comment by chorrell** [comment]
There are a few things I think we'll want to talk about:
- See where things diverge in the Dockerfiles and make a call on what we want to do there. I think docker-node has a slightly different slim variant and also has an additional wheezy variant. I also recently merged this: https://github.com/joyent/docker-node/pull/31. We'll want to incorporate that :)
- Update the docker-node README.md and LICENSE?
- Review the update process. For docker-node we have been handling updates for Node.js and npm separately. That will change with the upcoming merged version as I expect npm will be bundled with node-v$NODE_VERSION-linux-x64.tar.gz. I think it would also be good to just talk about general work-flow too. How do you generally handle releases?
- Review outstanding issues and pull requests. There are a few on the docker-node side that I left open since I wanted to have a broader discussion with the @nodejs/docker team (for example https://github.com/joyent/docker-node/pull/30 and https://github.com/joyent/docker-node/pull/11)
- Testing? For docker-node, we do a simple build test to shake out any obvious issues. I'd like to keep doing that and eventually do some more sophisticated testing (see https://github.com/joyent/docker-node/blob/master/test-build.sh and also my testing experiment here https://github.com/chorrell/docker-node/tree/serverspec-testing) 

Oh, also, I'm looking into dropping the 0.8 tag: https://github.com/joyent/docker-node/issues/34. v0.8.x hasn't been updated in a while, so it seems like an easy call to make. I'd like to wait until after the org switch though.

**Comment by retrohacker** [comment]
@chorrell re: testing. I've built https://github.com/wblankenship/dante to automate testing.

I created a branch https://github.com/wblankenship/docker-iojs/tree/tests that shows dante smoke testing iojs.

Really the only work left is getting it into a Jenkins buiild. I've setup a server for us on Digital Ocean, and started writing an ansible script to automate setting it up, but am only about half way there.

**Comment by retrohacker** [comment]
Noite: to run the tests, simply run `dante` in the root of that project. It reads `inventory.ini` and builds the dockerfiles and tests.

At this point, all we need to do is get it into Jenkins. Jenkins is pretty foreign to me, so if  someone knows there way around it and wants to tackle it, here is the current state of our jenkins build server: https://github.com/wblankenship/docker-integration

**Comment by chorrell** [comment]
Oh, interesting. Nice. 

Er, how do you install `dante`?

**Comment by retrohacker** [comment]
Good question. Right now I'm just building from source (`go install github.com/wblankenship/dante`).

Relatively new to go package distribution, I assume best practice here is to deliver a prebuilt binary? I'll cut a release now.

**Comment by retrohacker** [comment]
@chorrell woah, go's crosscompiling support is wicked awesome. Just cut a release, let me know if you have any problems with these binaries: https://github.com/wblankenship/dante/releases/tag/v1.0.0

**Comment by chorrell** [comment]
oh, nice! The `dante-darwin-amd64` binary worked just fine for me

**Comment by retrohacker** [comment]
@chorrell https://github.com/nodejs/build/issues/168

**Comment by chorrell** [comment]
:+1:

**Comment by chorrell** [comment]
Hi all,

I'm going to kick off the org switch today to move docker-node to the nodejs org.

After that I'm going to create a fork and work on testing a Node.js 4.0.0 RC-1 docker image to prep for a 4.0.0 release.

**Comment by chorrell** [comment]
Oh, and I'll handle the update and pull request for https://github.com/docker-library/official-images too :)

**Comment by chorrell** [comment]
"You don’t have admin rights to nodejs" Doh. That didn't work the way I expected it too...

Reading this: https://help.github.com/articles/transferring-a-repository/

> On the other end, the person transferring the repository also needs to have admin rights in the receiving organization. 

Apparently I need admin rights in nodejs...

**Comment by mikeal** [comment]
@chorrell can you add me to that repo? I can move the repo and add whatever teams you need on it.

**Comment by chorrell** [comment]
@mikeal Will do, thanks!

**Comment by chorrell** [comment]
Done, you should be an admin for the repo now

**Comment by mikeal** [comment]
I must be pulling up the wrong link, which repo am I transferring? :)

**Comment by chorrell** [comment]
https://github.com/joyent/docker-node

:)

**Comment by mikeal** [comment]
transferred, i added build, docker and docker-admin teams to it.

**Comment by chorrell** [comment]
Nice, thanks!

**Comment by Starefossen** [comment]
Thanks @mikeal

**Comment by chorrell** [comment]
@mikeal Hmm, I don't think the docker team has admin-type access yet: https://github.com/orgs/nodejs/teams/docker/repositories

**Comment by chorrell** [comment]
Or I just don't understand how teams and admin access etc work...

**Comment by rvagg** [comment]
I added docker-node to the repos list for that team, you should all now have admin on both repos

![screen shot 2015-09-05 at 11 29 10 am](https://cloud.githubusercontent.com/assets/495647/9697051/8f7f70f2-53c1-11e5-8d00-e4943203c31b.png)

**Comment by Starefossen** [comment]
@chorrell should we consolidate the docker repos or just discontinue the docker-iojs one?

**Comment by chorrell** [comment]
@Starefossen I think we should definitely consolidate some things. For instance I would love to the automated testing work added to the nodejs image: https://github.com/nodejs/docker-iojs/issues/46

**Comment by chorrell** [comment]
Oh, and the README!

**Comment by Starefossen** [comment]
I'm closing this now since the converge has been completed.
